### ISSUE TITLE
Removing cocktails from favorites

### ISSUE THREAD

**Issue by CreVL** [neNerower/cocktailme#4]
In favorites, there is no way to delete all cocktails at once, you have to delete each one individually.
![Screenshot_20220407-163253](https://user-images.githubusercontent.com/91658458/162215278-2e0b22ab-a1b2-48a2-921d-1bd010490fdd.png)

**Comment by neNerower** [comment]
Ok, currently this is not a bug
We will think later to add this feature especially for you.
